# Generated by Django 5.1.7 on 2025-05-16 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeKeyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.JSONField()),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_templates', to='category.pipe')),
            ],
        ),
    ]
