# Generated by Django 4.2.6 on 2025-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
