# Generated by Django 5.1.7 on 2025-03-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_subitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watertank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('sub_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watertank', to='category.subitem')),
            ],
        ),
    ]
