# Generated by Django 5.1.7 on 2025-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_pipekeytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
