# Generated by Django 5.1.7 on 2025-06-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_pipe_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipe',
            name='position',
        ),
    ]
