# Generated by Django 5.1.7 on 2025-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_pipe_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
