# Generated by Django 5.1.7 on 2025-09-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_pipe_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipeKeyTemplate',
        ),
    ]
