# Generated by Django 5.1.7 on 2025-03-31 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_item_category_remove_subitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='category.pipe'),
        ),
    ]
