# Generated by Django 5.1.7 on 2025-03-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_item_category_remove_subitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
