# Generated by Django 5.1.7 on 2025-04-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_pipe_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggel', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
