# Generated by Django 5.1.7 on 2025-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='marked_as_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
