# Generated by Django 5.1.7 on 2025-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_pipe_marked_as_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='MM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Packing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='Size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
