# Generated by Django 5.1.7 on 2025-04-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_pipe_code_pipe_mm_pipe_packing_pipe_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipe',
            old_name='Code',
            new_name='large_bag',
        ),
    ]
