# Generated by Django 4.2.6 on 2025-03-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='gst_number',
        ),
    ]
