# Generated by Django 5.1.7 on 2025-04-22 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_pipe_marked_as_favorite'),
        ('user', '0002_remove_usermodel_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(help_text='Discount percentage (e.g., 10 for 10%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='If specified, discount applies to this category and all its subcategories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='category.pipe')),
                ('product', models.ForeignKey(blank=True, help_text='If specified, discount applies only to this specific product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='category.pipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
