# Generated by Django 5.1.7 on 2025-06-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdiscount_price_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscount',
            name='discount_data',
            field=models.JSONField(blank=True, default=list, help_text='JSON structure containing all category and product discounts', null=True),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='price_data',
            field=models.JSONField(blank=True, default=list, help_text='JSON structure containing all category and product prices', null=True),
        ),
    ]
