# Generated by Django 5.1.7 on 2025-06-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdiscount_discount_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VENDOR', 'Vendor'), ('SUPERVISOR', 'Supervisor')], default='VENDOR', max_length=20),
        ),
    ]
