# Generated by Django 5.1.7 on 2025-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscount',
            name='discount_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
