# Generated by Django 5.1.7 on 2025-06-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role_flag',
            field=models.BooleanField(default=False),
        ),
    ]
