# Generated by Django 5.1.7 on 2025-04-22 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdiscount_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiscount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userdiscount',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='userdiscount',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='userdiscount',
            name='product',
        ),
        migrations.AddField(
            model_name='userdiscount',
            name='discount_data',
            field=models.JSONField(default=dict, help_text='JSON structure containing all category and product discounts'),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
