# Generated by Django 5.1.7 on 2025-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_invoice_discount_type_invoice_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
