# Generated by Django 5.1.7 on 2025-03-31 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_flag'),
        ('category', '0006_alter_pipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipe', to='category.pipe'),
        ),
    ]
