# Generated by Django 5.1.7 on 2025-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRM', 'Confirm'), ('COMPLETED', 'Completed'), ('CANCEL', 'Cancel')], default='PENDING', max_length=20),
        ),
    ]
