# Generated by Django 5.1.7 on 2025-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_old_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, default=False, max_length=250),
            preserve_default=False,
        ),
    ]
